# Generated by Django 3.1.7 on 2021-06-02 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='NewItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(choices=[('tshirt', 'Tshirt'), ('golfer', 'Golfer'), ('hoody', 'Hoody'), ('cap', 'Cap')], max_length=100)),
                ('size', models.CharField(choices=[('xs', 'Xsmall'), ('s', 'Small'), ('m', 'Medium'), ('l', 'Large'), ('xl', 'Xlarge')], max_length=2)),
                ('color', models.CharField(choices=[('blue', 'Blue'), ('green', 'Green'), ('black', 'Black'), ('yellow', 'Yellow'), ('grey', 'Grey')], max_length=10)),
                ('amount', models.IntegerField(default=True)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Capeteesstock.product')),
            ],
        ),
    ]
